{% set name = "tauso" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.10,<3.13
    - numpy >=2.0
    - pandas >=2.2
    - scipy >=1.11
    - numba >=0.60
    - matplotlib >=3.8
    - pytz
    - simplejson
    - tqdm
    - fuzzysearch
    - gffutils
    - biopython >=1.83
    - bcbio-gff
    - multiprocess
    - pympler
    - primer3-py
    - viennarna
    - gget >=0.29          # ← use bioconda package
    - codon-bias
test:
  commands:
    - python -c "import tauso"     # top-level package

about:
  home: https://github.com/RedPenguin100/TAUSO
  license: MIT
  license_file: LICENSE            # include if present in repo
  summary: "TAUSO: ASO design toolkit for antisense oligonucleotide development"
  description: |
    TAUSO provides computational tools for designing and optimizing antisense
    oligonucleotides, integrating accessibility modeling, off-target prediction,
    and machine-learning-based ranking.

extra:
  recipe-maintainers:
    - RedPenguin100