import pandas as pd

IDO1_sequence = "ACTGAGGGGCACCAGAGGAGCAGACTACAAGAATGGCACACGCTATGGAAAACTCCTGGACAATCAGTAAAGAGTACCATATTGATGAAGAAGTGGGCTTTGCTCTGCCAAATCCACAGGAAAATCTACCTGATTTTTATAATGACTGGATGTTCATTGCTAAACATCTGCCTGATCTCATAGAGTCTGGCCAGCTTCGAGAAAGAGTTGAGAAGTTAAACATGCTCAGCATTGATCATCTCACAGACCACAAGTCACAGCGCCTTGCACGTCTAGTTCTGGGATGCATCACCATGGCATATGTGTGGGGCAAAGGTCATGGAGATGTCCGTAAGGTCTTGCCAAGAAATATTGCTGTTCCTTACTGCCAACTCTCCAAGAAACTGGAACTGCCTCCTATTTTGGTTTATGCAGACTGTGTCTTGGCAAACTGGAAGAAAAAGGATCCTAATAAGCCCCTGACTTATGAGAACATGGACGTTTTGTTCTCATTTCGTGATGGAGACTGCAGTAAAGGATTCTTCCTGGTCTCTCTATTGGTGGAAATAGCAGCTGCTTCTGCAATCAAAGTAATTCCTACTGTATTCAAGGCAATGCAAATGCAAGAACGGGACACTTTGCTAAAGGCGCTGTTGGAAATAGCTTCTTGCTTGGAGAAAGCCCTTCAAGTGTTTCACCAAATCCACGATCATGTGAACCCAAAAGCATTTTTCAGTGTTCTTCGCATATATTTGTCTGGCTGGAAAGGCAACCCCCAGCTATCAGACGGTCTGGTGTATGAAGGGTTCTGGGAAGACCCAAAGGAGTTTGCAGGGGGCAGTGCAGGCCAAAGCAGCGTCTTTCAGTGCTTTGACGTCCTGCTGGGCATCCAGCAGACTGCTGGTGGAGGACATGCTGCTCAGTTCCTCCAGGACATGAGAAGATATATGCCACCAGCTCACAGGAACTTCCTGTGCTCATTAGAGTCAAATCCCTCAGTCCGTGAGTTTGTCCTTTCAAAAGGTGATGCTGGCCTGCGGGAAGCTTATGACGCCTGTGTGAAAGCTCTGGTCTCCCTGAGGAGCTACCATCTGCAAATCGTGACTAAGTACATCCTGATTCCTGCAAGCCAGCAGCCAAAGGAGAATAAGACCTCTGAAGACCCTTCAAAACTGGAAGCCAAAGGAACTGGAGGCACTGATTTAATGAATTTCCTGAAGACTGTAAGAAGTACAACTGAGAAATCCCTTTTGAAGGAAGGTTAATGTAACCCAACAAGAGCACATTTTATCATAGCAGAGACATCTGTATGCATTCCTGTCATTACCCATTGTAACAGAGCCACAAACTAATACTATGCAATGTTTTACCAATAATGCAATACAAAAGACCTCAAAATACCTGTGCATTTCTTGTAGGAAAACAACAAAAGGTAATTATGTGTAATTATACTAGAAGTTTTGTAATCTGTATCTTATCATTGGAATAAAATGACATTCAATAAATAAAAATGCATAAGATATATTCTGTCGGCTGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGCGGATCACAAGGTCAGGAGATCGAGACCATCTTGGCTAACACGGTGAAACCCCGTCTCTACTAAAAATACAAAAAATTAGCCGGGCGCGGTGGCGGGCACCTGTAGTCCCAGCTACTCGGGAGGCTGAGGCAGGAGAATGGCGTGAACCTGGGAGGCGGAGCTTGCAGTGAGCCAAGATTGTGCCACTGCAATCCGGCCTGGGCTAAAGAGCGGGACTCCGTCTCAAAAAAAAAAAAAAAAAGATATATTCTGTCATAATAAATAAAAATGCATAAGATATAA"
print(len(IDO1_sequence))

EFO12_exp = pd.read_csv("EFO21_experiments.csv")
SK0V3_exp = pd.read_csv("SK0V3_experiments.csv")

EFO12_exp["ASO"] = EFO12_exp["ASO"].str.upper()
SK0V3_exp["ASO"] = SK0V3_exp["ASO"].str.upper()

EFO12_exp["Sequence"] = EFO12_exp["Sequence"].str.upper()
SK0V3_exp["Sequence"] = SK0V3_exp["Sequence"].str.upper()

EFO12_exp["Experiment"] = "EFO21"
SK0V3_exp["Experiment"] = "SK0V3"

combined_exp = pd.concat([EFO12_exp, SK0V3_exp], ignore_index=True)

combined_exp = combined_exp.sort_values(by="ASO", ascending=True)

combined_exp.to_csv("IDO1_exp_data.csv", index=False)

#  ===============     Check for duplications      ======================

# aso_duplicates = combined_exp["ASO"][combined_exp["ASO"].duplicated()]
# seq_duplicates = combined_exp["Sequence"][combined_exp["Sequence"].duplicated()]
#
# print(aso_duplicates.unique(), len(aso_duplicates.unique()))
#
# print(seq_duplicates.unique(), len(seq_duplicates.unique()))


