name: tauso
channels:
  - conda-forge
  - bioconda
dependencies:
  - ruff==0.15.12
  - shap
  - jupyterlab
  - matplotlib
  - seaborn
  - ipykernel
  - optuna
  - cupy
  - graphviz
  - pip
  - pip:
    - -e .
  # tooling
  - pytest
  - pytest-regressions
  - pytest-xdist
  - conda-build
  - conda-lock
  - pandas-stubs
  - scipy-stubs
