name: tauso

channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.11
 # core python deps (no build pins)
  - requests
  - numpy==2.3.4
  - pandas
  - pyarrow
  - scipy
  - numba
  - biopython
  - bcbio-gff
  - gffutils
  - pyranges
  - fuzzysearch
  - primer3-py
  - tqdm
  - simplejson
  - pytz
  - tomli
  - zipp
  - pympler
  - multiprocess
  - click
  - gdown
  - mysql-connector-python
  - platformdirs

  - pybigwig # For ribo-seq
  - bowtie

  - codon-bias==0.3.5
  - viennarna==2.7.0
  - gget
  - xgboost

  - pandarallel