name: tauso

channels:
  - conda-forge
  - bioconda
dependencies:
  - ruff==0.15.12
  - jupyterlab
  - ipykernel
  - cupy
  - graphviz
  - uv
  - conda-build
  - conda-lock
  - pip:
    - -e ".[dev]"  # installs tauso + all runtime + dev extras
