name: tauso
channels:
  - conda-forge
dependencies:
  - ruff
  - shap
  - jupyterlab
  - matplotlib
  - seaborn
  - ipykernel
  - optuna
  - cupy
  - seaborn
  - graphviz
  - pip
  - pip:
    - -e .
    - ruff
  # tooling
  - pytest
  - pytest-regressions
  - pytest-xdist
  - conda-build
  - pandas-stubs